config/routes.rb
KcwWorld::Application.routes.draw do

  resources :categories
  resources :proverbs
  resources :photos
  resources :articles
    
  get 'home' => 'home#index', :as => :home
  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category

	scope :active, where('active = ?', true)
  	scope :alphabetical, order('title')
  	
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :photos
  has_many :articles
  
  scope :active, where('active = ?', true)
  scope :alphabetical, order('name')
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # Carrierwave
  mount_uploader :image, ImageUploader
  
  # Relationships
  belongs_to :category
  
  # Validations
  validates_presence_of :caption
  
  # Scopes
  scope :active, where('active = ?', true)
  scope :alphabetical, order('caption')
end

app/models/proverb.rb
class Proverb < ActiveRecord::Base
  # Method to get a random quote for home page
  def self.get_random_quote
    find(:first, :order => 'Random()')
  end
  
  # Make sure that both klingon phrase and translation included
  validates_presence_of :klingon, :translation
  
  # Alphabetical by translation
  scope :alphabetical, order('translation')
  scope :active, where('active = ?', true)
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.alphabetical.paginate(:page => params[:page]).per_page(10)
  end


  def show
    @article = Article.find(params[:id])
  end


  def new
    @article = Article.new
  end


  def edit
    @article = Article.find(params[:id])
  end


  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to article_path(@article)
    else
      render :action => "new"
    end
  end


  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Article was successfully updated.'
      redirect_to article_path(@article)
    else
      render :action => "edit"
    end
  end


  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.alphabetical.paginate(:page => params[:page]).per_page(10)
  end


  def show
    @category = Category.find(params[:id])
  end


  def new
    @category = Category.new
  end


  def edit
    @category = Category.find(params[:id])
  end


  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to category_path(@category)
    else
      render :action => "new"
    end
  end


  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = 'Category was successfully updated.'
      redirect_to category_path(@category)
    else
      render :action => "edit"
    end
  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @proverb = Proverb.get_random_quote
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    @photos = Photo.active.alphabetical.paginate(:page => params[:page]).per_page(5)
  end


  def show
    @photo = Photo.find(params[:id])
  end


  def new
    @photo = Photo.new
  end


  def edit
    @photo = Photo.find(params[:id])
  end


  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      flash[:notice] = 'Photo was successfully created.'
      redirect_to photo_path(@photo)
    else
      render :action => "new"
    end
  end


  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      flash[:notice] = 'Photo was successfully updated.'
      redirect_to photo_path(@photo)
    else
      render :action => "edit"
    end
  end


  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end
end

app/controllers/proverbs_controller.rb
class ProverbsController < ApplicationController
  
  def index
    @proverbs = Proverb.active.alphabetical.paginate(:page => params[:page]).per_page(10)
  end


  def show
    @proverb = Proverb.find(params[:id])
  end


  def new
    @proverb = Proverb.new
  end


  def edit
    @proverb = Proverb.find(params[:id])
    flash[:notice] = 'Revise proverbs only if there is a typo; altering its meaning will cost you your life.'
  end


  def create
    @proverb = Proverb.new(params[:proverb])
    if @proverb.save
      flash[:notice] = 'A new proverb was successfully created.'
      redirect_to proverb_path(@proverb)
    else
      render :action => "new"
    end
  end


  def update
    @proverb = Proverb.find(params[:id])
    if @proverb.update_attributes(params[:proverb])
      flash[:notice] = 'Proverb was successfully updated ...and for your sake it better be correct.'
      redirect_to proverb_path(@proverb)
    else
      render :action => "edit"
    end
  end


  def destroy
    @proverb = Proverb.find(params[:id])
    flash[:error] = 'petaQ! You cannot destroy a hallowed Klingon proverb. '
    redirect_to proverbs_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Article</legend>

		<%= f.input :title %>
		<%= f.input :content %>
		<%= f.input :category_id, :collection => Category.active.alphabetical, :include_blank => true %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', articles_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/articles/edit.html.erb
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h2>Articles</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
			<th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td>
				<td><%= article.category.name %></td>
        <td>
          <%= link_to 'Edit', edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', article_path(article), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

<%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p>
  <%= @article.content %>
</p>

<p>&nbsp;</p>

<p>
  <b>Category</b>: 
  <%= @article.category.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', articles_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_article_path(@article), :class => 'btn' %>
  <%= link_to 'Delete', article_path(@article), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Category</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :active, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :active, :class => 'check_box' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', categories_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td>
          <%= link_to 'Edit', edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', category_path(category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path, :class => 'btn btn-primary' %>

app/views/categories/show.html.erb
<h1>Category</h1>

<p>
  <b>Name</b><br>
  <%= @category.name %>
</p>

<p>
  <b>Active</b><br>
  <%= @category.active %>
</p>

<div class="form-actions">
  <%= link_to 'Back', categories_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_category_path(@category), :class => 'btn' %>
  <%= link_to 'Delete', category_path(@category), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<p>This site is designed to inspire Klingon code warriors with a randomly selected quote from a collection of Klingon wisdom.  Today's quote of the day is as follows:</p>
<p class="supertiny">&nbsp;</p>
<% unless @proverb.nil? %>
	<p class="klingon"><%= @proverb.klingon %></p><br>
	<p class="translation"><%= @proverb.translation %></p>
<% end %>
<p>&nbsp;</p>
<p>&nbsp;</p>
<%= link_to 'Add a new Klingon proverb to our list', new_proverb_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>quv vIt :: <%= controller.controller_name.capitalize %></title>
	<%= stylesheet_link_tag "application", "bootstrap.min", "bootstrap-responsive.min" %>
  <%= javascript_include_tag "jquery-1.7.2.min", "jquery-ui.min", "jquery_ujs", "bootstrap.min", "application" %>
  <%= csrf_meta_tags %>
	
</head>
<body>
	<%= link_to(image_tag('quv_vIt.gif'), home_path) %>
	<div id="wrapper">
		<div class="navbar">
		  <div class="navbar-inner">
		    <div class="container">
		      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>
		      <div class="nav-collapse">
		        <ul class="nav">
							<li><%= link_to "Home", home_path %></li>
		          <li><%= link_to "Proverbs", proverbs_path %></li>
							<li><%= link_to "Photos", photos_path %></li>
							<li><%= link_to "Categories", categories_path %></li>
		        </ul>
		      </div>
		    </div>
		  </div>
		</div>

		<!-- MAIN CONTENT -->
		<div class="container">
			<!-- flash messages -->
			<% flash.each do |name, msg| %>
				<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
					<a class="close" data-dismiss="alert">&times;</a>
					<%= msg %>
				</div>
	    <% end %>
			<div class="row">
				<!-- main content placed here -->
				<div class="span12">
					<%= yield %>
				</div>
			</div>
		</div>

		<!-- FOOTER -->
		<footer id="footer">
	    <div class="container">
				<%= render :partial => "partials/footer" %>
	    </div>
	  </footer>
	</div>
</body>
</html>

app/views/partials/_add_comments_to_page.html.erb
<p>
	<strong><%= obj.comments.size.zero? ? "No comments yet" : pluralize(obj.comments.size, 'comment') %> on this <%= "#{obj.class.to_s.downcase}" %></strong><br>
	<% unless @comments.empty? || @comments.nil? %>
		<%= render :partial => "partials/comment_list" %>
	<% end %>
</p>
<p>
	<%= render :partial => "partials/comment_form" %>
</p>

app/views/partials/_comment_form.html.erb
<p class="supertiny">&nbsp;</p>
<h3>Add a Comment</h3><br />

<%= form_for([@commentable, Comment.new], :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>
 
    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => 'text_area', :rows => 4 %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', comments_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/partials/_comment_list.html.erb
<div id="comments">
<% for comment in @comments %>
  <div class="comment">
    <%= comment.content %><br>	
		by <strong><%= mail_to comment.email, comment.name, :encode => "javascript" %></strong>
	  <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
  </div>
<% end %>
</div>

app/views/partials/_footer.html.erb
<div id="footer">
	
	<div id="copy">
		Webmaster: <%= mail_to("your_andrew_id@andrew.cmu.edu", "YOUR NAME HERE", :encode => "javascript") %> 
		&nbsp;&nbsp;&copy 2012 
		<br />The date and time is now: <%= Time.now.strftime("%B %e, %Y at %I:%M:%S %P") %>
	</div>

</div>

app/views/photos/_form.html.erb
<%= simple_form_for @photo, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Photo</legend>

		<%= f.input :caption %>
		<%= f.input :image %>
		<%= f.input :category_id, :collection => Category.active.alphabetical, :include_blank => true %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', photos_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/photos/index.html.erb
<h2>Photos</h2>
<table class="table table-striped">
  <thead>
    <tr>
			<th>&nbsp;</th>
      <th>Caption</th>
			<th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
				<td><%= image_tag photo.image_url %></td>
        <td><%= link_to photo.caption, photo_path(photo) %></td>
				<td><%= photo.category.name %></td>
        <td>
          <%= link_to 'Edit', edit_photo_path(photo), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', photo_path(photo), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @photos, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>


<%= link_to 'New Photo', new_photo_path, :class => 'btn btn-primary' %>

app/views/photos/show.html.erb
<p>
  <% unless @photo.image_url.nil? %> 
		<p><%= image_tag @photo.image_url %></p>
	<% end %>
  <%= @photo.caption %>
</p>

<p>&nbsp;</p>

<p>
  <b>Category</b>: 
  <%= @photo.category.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', photos_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_photo_path(@photo), :class => 'btn' %>
  <%= link_to 'Delete', photo_path(@photo), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/proverbs/_form.html.erb
<%= simple_form_for @proverb, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Proverb</legend>

		<%= f.input :klingon %>
		<%= f.input :translation %>
    <%# f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', proverbs_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/proverbs/index.html.erb
<h2>Proverbs</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Klingon</th>
      <th>Translation</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @proverbs.each do |proverb| %>
      <tr>
        <td><%= link_to proverb.klingon, proverb_path(proverb) %></td>
        <td><%= proverb.translation %></td>
        <td>
          <%= link_to 'Edit', edit_proverb_path(proverb), :class => 'btn btn-mini' %>
          <%= link_to "Don't even try it...", proverb_path(proverb), :method => :delete, :confirm => 'A Qovpatlh like you dares to destroy a cherished Klingon proverb? I think not.', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @proverbs, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

<%= link_to 'New Proverb', new_proverb_path, :class => 'btn btn-primary' %>

app/views/proverbs/show.html.erb
<h2><%= @proverb.klingon %></h2>

<p>
  <b>Translation</b>:
  <em><%= @proverb.translation %></em>
</p>

<p>
  <b>Active</b>: 
  <%= @proverb.active ? "Of course" : "No" %>
</p>

<div class="form-actions">
  <%= link_to 'Back', proverbs_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_proverb_path(@proverb), :class => 'btn' %>
  <%= link_to "Seriously, don't try it", proverb_path(@proverb), :method => 'delete', :confirm => 'A Qovpatlh like you dares to destroy a cherished Klingon proverb? I think not.', :class => 'btn btn-danger' %>
</div>